### ISSUE TITLE
Published docs tab and page shows a placeholder name

### ISSUE THREAD

**Issue by sgjholt** [k-a-mendoza/Pyrrhenius#1]
<img width="1105" alt="Screenshot 2024-09-01 at 2 17 52 PM" src="https://github.com/user-attachments/assets/a1d917e3-afda-413a-a7e8-de9cb664df6a">

I suggest labeling this page as `For Developers: Coming Soon!`, `For Developers: Under Construction ...`, or some other placeholder title. I think it will just present a little better for the time being!

Should be as simple as just changing the title in this file:
https://github.com/k-a-mendoza/Pyrrhenius/blob/main/docs/source/fordevelopers.rst

**Comment by k-a-mendoza** [comment]
the "test title" was a placeholder for the API. API is now fully documented with docstrings and examples. Closing issue with merge #12
