### ISSUE TITLE
Suggest moving hard coded variables to a default configuration file (ideally that may be replaced with a custom one)

### ISSUE THREAD

**Issue by sgjholt** [k-a-mendoza/Pyrrhenius#8]
It would be nice to have any hard coded numbers (especially physical quantities) in one place. It would also be nice to be able to change them, even if you physically shouldn't. I think the way you have it set up now multiple class instances of Mechanism would share the same hard coded parameters, as they are tied to the class pre-init. So, if you wanted to test several `Mechanism` with differing variables, post-init, you wouldn't be able to change one without modifying all of the other instances. I don't know if that was the desired behavior, but I would think about changing that. At the very least I think assigning them post-init would be more desirable behaviour. 

 
https://github.com/k-a-mendoza/Pyrrhenius/blob/7f239fc750e71a892d0c01f4be848d53ac4435a0/pyrrhenius/mechanisms.py#L17

**Comment by k-a-mendoza** [comment]
do you mean these potentially? 

```python
 k = 8.617333262e-5 # in ev/k
    q = 1.602176634e-19 # charge of electron
    q2 =(1.602176634e-19)**2
    r = 8.31446261815324e-3 # gas constant in kj/mol
    cm3GPamol_to_ev = 1/96.49 # converts pressure*cm^3/mol volume to ev
```

**Comment by sgjholt** [comment]
> do you mean these potentially? 
> 
> 
> 
> ```python
> 
>  k = 8.617333262e-5 # in ev/k
> 
>     q = 1.602176634e-19 # charge of electron
> 
>     q2 =(1.602176634e-19)**2
> 
>     r = 8.31446261815324e-3 # gas constant in kj/mol
> 
>     cm3GPamol_to_ev = 1/96.49 # converts pressure*cm^3/mol volume to ev
> 
> ```
> 
> 
> 
> 

Yes! Exactly these. I should have referenced them in the issue, sorry!

**Comment by k-a-mendoza** [comment]
Great Suggestion @sgjholt. The big change was to add a .json file within the pyrrhenius module. Minor changes were made within the mechanisms base class and elsewhere to get unit tests to pass. Issue addressed with pull request https://github.com/k-a-mendoza/Pyrrhenius/pull/9#issue-2501919285
